// Contenido de la guía de exposición. Cada paso = texto en pantalla + estado de la escena 3D.
const PARTES = ['El problema', 'Qué es un monolito', 'Cómo está hecha', 'Un pedido por dentro', 'Ventajas, límites y cierre'];

const PASOS = [
  { parte: 1, titulo: 'Formosa produce. Pero vende a través de otros.',
    texto: 'Zapallo en Ibarreta, miel en Las Lomitas, queso en Pirané. Entre la chacra y la mesa aparece un intermediario que pone el precio. El productor cobra menos y el comprador no sabe de dónde viene lo que come.',
    escena: { camara: 'problema', flujo: 'intermediario', monolito: false, intermediario: true, explotar: 0, etiquetas: ['pines', 'rios', 'inter', 'capital'], foco: [], recorrido: false, limites: false, orbita: false } },
  { parte: 1, titulo: 'Mercado Chacarero: directo de la chacra',
    texto: 'Una app web donde el productor publica sus productos, fija su precio y recibe pedidos directo. El comprador ve quién lo produjo y en qué localidad.',
    puntos: ['El productor publica y controla su stock', 'El comprador arma el carrito y elige retiro o envío', 'El Estado ve cuánto vende cada zona'],
    escena: { camara: 'propuesta', flujo: 'directo', monolito: true, intermediario: false, etiquetas: ['pines', 'rios', 'proceso'], foco: [], orbita: false } },
  { parte: 2, titulo: 'Un monolito: todo en un solo bloque',
    texto: 'Toda la aplicación es una sola unidad. La pantalla, las reglas y el acceso a datos viajan juntos.',
    puntos: ['Un solo código fuente', 'Un solo proceso: npm start', 'Un solo despliegue', 'Una sola base de datos'],
    vivo: 'pid',
    escena: { camara: 'bloque', flujo: null, explotar: 0, etiquetas: ['proceso', 'db'], foco: [], orbita: true } },
  { parte: 2, titulo: 'Por dentro, ordenado en capas',
    texto: 'Que sea un bloque no significa que sea un desorden. Cada capa tiene un trabajo y se comunica con la de al lado llamando funciones, no mandando mensajes por internet.',
    puntos: ['Vistas: arman el HTML', 'Rutas: reciben cada pedido del navegador', 'Servicios: aplican las reglas del negocio', 'Base de datos: guarda todo'],
    escena: { camara: 'capas', explotar: 1, etiquetas: ['capas', 'db', 'navegador'], foco: ['vistas', 'rutas', 'servicios', 'db'], orbita: false } },
  { parte: 3, titulo: 'Cuatro módulos, un mismo programa',
    texto: 'Separamos el código por responsabilidad. Comparten proceso y base de datos, pero cada uno tiene su carpeta y su frontera.',
    puntos: ['usuarios: registro, ingreso y roles', 'catalogo: publicar y buscar productos', 'pedidos: carrito, stock y estados', 'reportes: resumen del productor y tablero provincial'],
    codigo: 'src/modulos/',
    escena: { camara: 'modulos', explotar: 0.35, etiquetas: ['modulos', 'capas'], foco: ['modulos'], orbita: false } },
  { parte: 3, titulo: 'Una sola base de datos: PostgreSQL',
    texto: 'Usuarios, productos, pedidos y hasta las sesiones viven en la misma base. Por eso una compra se resuelve en una sola transacción: o se guarda todo, o no se guarda nada.',
    vivo: 'numeros',
    escena: { camara: 'db', explotar: 0, etiquetas: ['db', 'modulos'], foco: ['db'], orbita: false } },
  { parte: 4, titulo: 'El viaje de un pedido',
    texto: 'Laura, de Formosa capital, le compra mandioca a don Ramón de Ibarreta. Seguí la luz.',
    fases: ['Laura toca "Enviar pedido"', 'La ruta POST /carrito/confirmar lo recibe', 'El servicio de Pedidos abre una transacción', 'PostgreSQL descuenta stock y guarda el pedido', 'Todo salió bien: COMMIT. Si algo falla: ROLLBACK', 'La vista EJS arma la página Mis compras', 'Laura ve su pedido, en milisegundos'],
    escena: { camara: 'recorrido', flujo: null, explotar: 0.6, etiquetas: ['capas', 'navegador', 'db', 'modulos'], foco: [], recorrido: true, orbita: false } },
  { parte: 4, titulo: 'Demo en vivo',
    texto: 'Lo que viste en 3D, ahora funcionando. La app y esta guía las atiende el mismo proceso.',
    demo: [['Ingresar como Laura (compradora)', '/ingresar?sig=/productos'], ['Ver el catálogo', '/productos'], ['Panel de don Ramón (productor)', '/panel/ventas'], ['Tablero provincial (admin)', '/tablero']],
    vivo: 'pid',
    escena: { camara: 'demo', explotar: 0, recorrido: false, etiquetas: ['proceso'], foco: [], orbita: true } },
  { parte: 5, titulo: 'Por qué elegimos un monolito',
    texto: 'Para un equipo chico y un problema que recién empieza, lo simple gana.',
    puntos: ['Se desarrolla y se prueba en una sola compu', 'Un único despliegue: un servidor alcanza', 'Las transacciones son naturales: una sola base', 'Rápido: los módulos se llaman sin red de por medio'],
    escena: { camara: 'bloque', flujo: 'directo', explotar: 0, etiquetas: ['proceso', 'db'], foco: ['servicios', 'rutas', 'vistas', 'db'], limites: false, orbita: true } },
  { parte: 5, titulo: 'Sus límites, sin esconderlos',
    texto: 'Para atender a más gente hay que copiar el sistema entero, aunque solo una parte esté cargada. Y si una parte falla sin control, puede tumbar todo el proceso.',
    puntos: ['Escala en bloque, no por partes: cada copia carga todo', 'Las copias comparten la misma base de datos', 'Un error grave afecta a todos los módulos', 'Cambiar de tecnología cuesta más'],
    escena: { camara: 'limites', flujo: null, etiquetas: ['copias', 'proceso'], foco: [], limites: true, orbita: false } },
  { parte: 5, titulo: 'Arquitectura simple. Problema real.',
    texto: 'No elegimos la arquitectura más moderna: elegimos la justa. Cuando Mercado Chacarero crezca, sus módulos ya están listos para separarse. Hoy, lo importante es que la mandioca de Ibarreta llegue directo a tu mesa.',
    vivo: 'numeros',
    escena: { camara: 'cierre', flujo: 'directo', limites: false, etiquetas: ['pines', 'rios', 'proceso'], foco: [], orbita: true } },
];
module.exports = { PARTES, PASOS };
